apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::874285202353:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-66KJL0UCGMVH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::874285202353:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-13T18:11:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-13T18:11:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1550"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0cddae35-85d0-4e40-9ed6-027fc626bc03
